---
# tasks file for php-fpm
- block:
  - name: apt key
    get_url:
      url: "{{ php_sury_apt_key_url }}"
      dest: "{{ php_sury_apt_key }}"
      mode: 0644
    # https://github.com/ansible/ansible/issues/65687
    when: not ansible_check_mode
    tags:
      - php-fpm
      - apt
      - key

  - name: sury repo
    template:
      src: php.list.j2
      dest: /etc/apt/sources.list.d/php.list
      mode: 0644
    tags:
      - php-fpm
      - apt
      - repository

  when:
    - php_origin is defined
    - php_origin == "sury"

- name: package
  package:
    name: "php{{ item }}-fpm"
    update_cache: true
  loop: "{{ php_versions }}"
  tags:
    - php-fpm
    - package

# - name: "check default pool(s)"
#   stat:
#     path: "/etc/php/{{ item }}/fpm/pool.d/www.conf"
#   register: defpool
#   tags:
#     - php-fpm
#     - defpool

# - name: "disable default pool(s)"
#   command: "mv /etc/php/{{ php_version | default('7.4') }}/fpm/pool.d/www.conf \
#     /etc/php/{{ php_version | default('7.4') }}/fpm/pool.d/www.conf.off"
#   when:
#     - defpool.stat.exists
#     - fpm_pools is defined
#   tags:
#     - php-fpm
#     - defpool

- name: "configure pool(s)"
  template:
    src: php-fpm-pool.conf.j2
    dest: "/etc/php/{{ item.php_version }}/fpm/pool.d/{{ item.name }}.conf"
    mode: 0644
    backup: true
  loop: "{{ fpm_pools }}"
  notify: php-fpm restart
  when:
    - fpm_pools is defined
  tags:
    - php-fpm
    - pools
