---
# tasks file for php-fpm
- name: sury repo key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
  when:
    - php_origin is defined
    - php_origin == "sury"
  tags:
    - php-fpm
    - apt
    - key

- name: sury repo
  apt_repository:
    filename: php
    repo: 'deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main'
  when:
    - php_origin is defined
    - php_origin == "sury"
  register: repo
  tags:
    - php-fpm
    - apt
    - repository

- name: package
  package:
    name: "php{{ php_version }}-fpm"
    force_apt_get: yes
  when:
    - not ansible_check_mode
    - repo is succeeded
  tags:
    - php-fpm
    - package

- name: check default pool
  stat:
    path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
  register: defpool
  tags:
    - php-fpm
    - defpool

- name: disable default pool
  command: 'mv /etc/php/{{ php_version }}/fpm/pool.d/www.conf /etc/php/{{ php_version }}/fpm/pool.d/www.conf.off'
  when:
    - defpool.stat.exists
    - fpm_pools is defined
  tags:
    - php-fpm
    - defpool

- name: "configure pool(s)"
  template:
    src: php-fpm-pool.conf.j2
    dest: '/etc/php/{{ php_version }}/fpm/pool.d/{{ item.name }}.conf'
    backup: yes
  loop: "{{ fpm_pools }}"
  notify: php-fpm restart
  when:
    - fpm_pools is defined
  tags:
    - php-fpm
    - pools
...
