---
# tasks file for php-fpm
- name: origin
  when:
    - php_origin is defined
    - php_origin == "sury"
  block:
    - name: apt key
      ansible.builtin.get_url:
        url: "{{ php_sury_apt_key_url }}"
        dest: "{{ php_sury_apt_key }}"
        mode: 0644
      # https://github.com/ansible/ansible/issues/65687
      # when: not ansible_check_mode
      tags:
        - php-fpm
        - apt
        - key

    - name: sury repo
      ansible.builtin.template:
        src: php.list.j2
        dest: "/etc/apt/sources.list.d/{{ php_sury_file }}.list"
        mode: 0644
      tags:
        - php-fpm
        - apt
        - repository

    - name: stat
      ansible.builtin.stat:
        path: "/etc/apt/sources.list.d/{{ php_sury_file }}.list"
      register: repo
      tags:
        - php-fpm
        - apt
        - repository

- name: package
  ansible.builtin.package:
    name: "php{{ item }}-fpm"
    update_cache: true
  loop: "{{ php_versions }}"
  when:
    ( php_origin is undefined or php_origin == "default" ) or
    ( php_origin == "sury" and repo.stat.exists )
  tags:
    - php-fpm
    - package

- name: Modules
  ansible.builtin.package:
    name: "php{{ item.0 }}-{{ item.1 }}"
    update_cache: true
  loop: "{{ php_versions | product(php_modules) }}"
  when:
    - php_modules is defined
    - ( php_origin is undefined or php_origin == "default" ) or
      ( php_origin == "sury" and repo.stat.exists )
  tags:
    - php-fpm
    - package
    - modules

- name: Divert www pool
  community.general.dpkg_divert:
    path:
      "/etc/php/{{ item.php_version }}/fpm/pool.d/www.conf"
    divert:
      "/etc/php/{{ item.php_version }}/fpm/pool.d/www.conf.distrib"
    rename: true
  loop: "{{ fpm_pools }}"
  notify: Reload php-fpm
  when:
    - fpm_pools is defined
    - item.name == "www"
  tags:
    - php-fpm
    - pools
    - divert

- name: Configure pools
  ansible.builtin.template:
    src: php-fpm-pool.conf.j2
    dest:
      "/etc/php/{{ item.php_version }}/fpm/pool.d/{{ item.name }}.conf"
    mode: 0644
    backup: true
  loop: "{{ fpm_pools }}"
  notify: Reload php-fpm
  when:
    - fpm_pools is defined
  tags:
    - php-fpm
    - pools
    - template

- name: Config
  ansible.builtin.import_tasks: config.yml
  tags:
    - php-fpm
    - config

- name: Stat
  ansible.builtin.stat:
    path: "/usr/bin/php{{ php_version | default(omit) }}"
  register: alternative_target
  tags:
    - php-fpm
    - alternatives

- name: Alternatives
  community.general.alternatives:
    name: php
    path: "/usr/bin/php{{ php_version | default(omit) }}"
    state: selected
  when:
    - php_alternatives is defined
    - php_alternatives is true
    - alternative_target.stat.exists
  tags:
    - php-fpm
    - alternatives
