---
# handlers file for php-fpm
- name: php-fpm restart
  ansible.builtin.service:
    name: "php{{ item }}-fpm"
    state: restarted
  loop: "{{ php_versions }}"
  when:
    - not ansible_check_mode
