---
# handlers file for php-fpm
- name: Restart php-fpm
  ansible.builtin.service:
    name: "php{{ item }}-fpm"
    state: restarted
  loop: "{{ php_versions }}"
  when:
    - not ansible_check_mode

- name: Reload php-fpm
  ansible.builtin.service:
    name: "php{{ item }}-fpm"
    state: reloaded
  loop: "{{ php_versions }}"
  when:
    - not ansible_check_mode
